POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NGNkNzQwZjE4NWRlY2NkY2Y3YWE5NTciLCJpYXQiOjE2OTEyNzQ1NDR9.dt8UJ-3YOoyUbToV1duQzc_z7H8MTbn6s53_hUeBJMc
{
    "title": "Test2", 
    "author": "Sophia V. Prater",
    "url": "https://test.com/",
    "likes": 550
}