POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Voice Content and Usability", 
    "author": "Preston So",
    "url": "https://alistapart.com/article/voice-content-and-usability/",
    "likes": 415
}